name: Post to Teams

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *" # Runs daily at 9 PM CET

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11'

      - name: Install Dependencies
        run: yarn install

      - name: Run the Application
        run: |
          echo "LEADERBOARD_ID=${{ env.LEADERBOARD_ID }}" >> $GITHUB_ENV
          echo "YEAR=${{ env.YEAR }}" >> $GITHUB_ENV
          echo "TEAMS_WEBHOOK_URL=${{ secrets.TEAMS_WEBHOOK_URL }}" >> $GITHUB_ENV
          echo "SESSION_COOKIE=${{ secrets.SESSION_COOKIE }}" >> $GITHUB_ENV
          node app.js
